server:
  port: 8080

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:h2:mem:gatewaydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0

account:
  service:
    url: http://localhost:8081

resilience4j.circuitbreaker:
  instances:
    accountService:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 50